name: Package Hunters Wild
on: [push, workflow_dispatch]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: HuntersWild-Project
          path: .
